services:
  photon:
    image: ghcr.io/tomudding/photon-docker:0.6.1-graalvm23.0.1-ol9
    volumes:
      - photon_data:/photon/photon_data
    ports:
      - "2322:2322"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  photon_data:
